### ISSUE TITLE
TypeError: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by ptandler** [christophehurpeau/deep-freeze-es6#65]
Would be nice if I could call `deepFreeze()` with _anything_ as argument, for cases where the argument might be null or undefined (or anything else). 

You could simple move the check if obj should be frozen to the top, but it might be more performant to avoid function calls for all property values that cannot be frozen anyway. Maybe add a wrapper function that includes a check of the original argument? Hm, not sure.

**Comment by christophehurpeau** [comment]
What would be the use case ? freezing null or undefined doesnt feels right to me. I think the function should only accept freezable objects, but I am open to change

**Comment by ptandler** [comment]
My use case is when I want to freeze an object that is passed to a function that _might_ be null or undefined. In these cases it should simply do nothing and return the argument as it is. It just avoids extra checking before calling deepFreeze. (At the moment I added a deepFreeze2() wrapper that simply adds this check.) So I'd prefer to be able to pass anything to deepFreeze() and if it's not freezable, then just return as it is. null and numbers are immutable anyway.

**Comment by mk-pmb** [comment]
Do I understand correctly that with the new patch, the tests enshrine the existing behavior? I guess that means the request is denied. Sad. In that case, please at least warn in the README that it will throw for false-y values, so people can know without having to test.
